migrate:

	python3 manage.py makemigrations && python3 manage.py migrate

run:

	python3 manage.py runserver

reset:

	sudo fuser -k 8000/tcp - reset port in UBUNTU to default

admin:

	python3 manage.py createsuperuser

static:

	python3 manage.py collectstatic
